# Generated by Django 5.1.3 on 2024-12-13 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_image_dataset_remove_image_file_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('unlabeled', 'Unlabeled'), ('machine_labeled', 'Machine Labeled'), ('annotated', 'Annotated'), ('verified', 'Verified')], default='unlabeled', max_length=20),
        ),
        migrations.AddField(
            model_name='keypointannotation',
            name='annotation_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keypointannotation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='keypointannotation',
            name='annotator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL),
        ),
    ]
