# Generated by Django 5.1.3 on 2024-12-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_annotation_auditlog_batch_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('annotator', 'Annotator'), ('verifier', 'Verifier'), ('viewer', 'Viewer')], default='user', max_length=10),
        ),
    ]
