# Generated by Django 5.1.3 on 2024-12-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_role_delete_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('annotator', 'Annotator'), ('verifier', 'Verifier'), ('viewer', 'Viewer')], default=models.CharField(choices=[('admin', 'Admin'), ('annotator', 'Annotator'), ('verifier', 'Verifier'), ('viewer', 'Viewer')], default='admin', max_length=10), max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('annotator', 'Annotator'), ('verifier', 'Verifier'), ('viewer', 'Viewer')], default='admin', max_length=10),
        ),
    ]
