# Generated by Django 5.1.3 on 2024-12-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_role_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='file',
            field=models.ImageField(default=1, upload_to='pending_annotations/'),
            preserve_default=False,
        ),
    ]
