# Generated by Django 5.1.3 on 2024-12-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_annotation_verifier_alter_annotation_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('annotator', 'Annotator'), ('verifier', 'Verifier'), ('viewer', 'Viewer')], max_length=20),
        ),
    ]
