# Generated by Django 5.1.3 on 2024-12-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_images', models.IntegerField(default=0)),
                ('total_annotations', models.IntegerField(default=0)),
                ('pending_verifications', models.IntegerField(default=0)),
                ('verified_annotations', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
