# Generated by Django 5.1.3 on 2024-12-25 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_annotation_feedback_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='feedback',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
