# Generated by Django 5.1.3 on 2024-12-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_annotation_feedback_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
